server:
    port: ${PORT:5000}
    servlet: 
        context-path: /
        
# OAuth2 Environment Variables
oauth2-config:
    oauth2-server-url: ${SERVER_URL:https://development-oauth-server.herokuapp.com}
    oauth2-client-id: ${CLIENT_ID:1defe81df9442d2b74c2}
    oauth2-client-secret: ${CLIENT_SECRET:72e9208c85fed78cb43fec9f953662664ab5f649}

# Sentry Environment Variables
sentry-config:
    sentry-dsn: ${SENTRY_DSN}
    
spring: 
    datasource:
        url: jdbc:postgresql://ec2-3-221-72-63.compute-1.amazonaws.com:5432/de6vte08bnpfce?useSSL=true&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        username: uftkhdankcc1tn
        password: p99e08e52eeafd8423591f3eb1cab579142a614f0dd8645fa7855baa8a279ab63

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:    
                    use_jdbc_metadata_defaults: false

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-request-size: 215MB
            max-file-size: 200MB
    

security:
    oauth2:
        client:
            clientId: ${oauth2-config.oauth2-client-id}
            clientSecret: ${oauth2-config.oauth2-client-secret}
            accessTokenUri: ${oauth2-config.oauth2-server-url}/oauth/token
            userAuthorizationUri: ${oauth2-config.oauth2-server-url}/oauth/authorize

        resource:
            userInfoUri: ${oauth2-config.oauth2-server-url}/user/info
            tokenInfoUri: ${oauth2-config.oauth2-server-url}/oauth/check_token
            filter_order: 3
            


## MULTIPART (MultipartProperties)
# Enable multipart uploads
# spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
# spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
# spring.servlet.multipart.max-file-size=200MB
# Max Request Size
# spring.servlet.multipart.max-request-size=215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
# file.upload-dir=./uploads